import { ApiProperty } from '@nestjs/swagger';
import { Exclude, Expose } from 'class-transformer';
import { IsInt, Min } from 'class-validator';

export class DepositRequestDto {
  @ApiProperty({
    example: 5000,
    description: 'Amount in Kobo (₦50.00 → 5000). Must be at least 1 Kobo.',
  })
  @IsInt()
  @Min(1)
  amount: number;
}

@Exclude()
export class DepositResponseDto {
  @Expose()
  @ApiProperty({
    example: 'p7z0q9p2x1',
    description: 'Unique reference generated by Paystack',
  })
  reference: string;

  @Expose()
  @ApiProperty({
    example: 'https://checkout.paystack.com/abcdef12345',
    description: 'URL where the user should complete payment',
  })
  authorization_url: string;

  constructor(partial: Partial<DepositResponseDto>) {
    Object.assign(this, partial);
  }
}
